version: '2.1'
services:

  postgres:
    image: docker.io/postgres:10
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432"
    environment:
      POSTGRES_USER: passwordpusher_user
      POSTGRES_PASSWORD: passwordpusher_passwd
      POSTGRES_DB: passwordpusher_db

  passwordpusher:
    # dockerfile: Dockerfile
    build: .
    ports:
      - "5000"
    depends_on:
      - postgres

  reverse-proxy:
    # dockerfile: reverse-proxy/Dockerfile
    build: ./reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - passwordpusher

